---
title: "Population"
execute: 
  echo: false
  warning: false
---

```{r}
library(tidyverse)

v_labs <- read_csv("../_data/v_labs.csv")
acs1_single <- read_csv("../_data/acs1_single.csv")
acs1_multi <- read_csv("../_data/acs1_multi.csv") %>% 
  left_join(v_labs, by = c("variable" = "name"))
```

## Households

```{r}
hh <- acs1_multi %>% 
  filter(variable == "B25002_002")

hh %>% ggplot(aes(yr, estimate, group = 1)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number(scale = .001, suffix = "K")) +
  theme_minimal() +
  labs(x = "", y = "",
       title = "Number of Households",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25002_002)")
```

## Total Population in Occupied Housing Units

```{r}
tpohu <- acs1_multi %>% 
  filter(variable == "B25008_001")

tpohu %>% ggplot(aes(yr, estimate, group = 1)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number(scale = .001, suffix = "K")) +
  theme_minimal() +
  labs(x = "", y = "",
       title = "Total Population in Occupied Housing Units",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25008)")
```

## Average Household Size

```{r}
ahhs <- acs1_multi %>% 
  filter(variable == "B25010_001")

ahhs %>% ggplot(aes(yr, estimate, group = 1)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number()) +
  theme_minimal() +
  labs(x = "", y = "",
       title = "Average Household Size",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25008)")
```

## Race of Householder

```{r}
race <- acs1_multi %>% 
  filter(str_detect(variable, "B25006(?!_001)")) %>% 
  mutate(lab = str_remove_all(lab, "(Householder who is)|(alone)")) %>% 
  group_by(yr) %>% 
  arrange(estimate) %>% 
  ungroup() %>% 
  mutate(lab = fct_inorder(lab))


race %>% ggplot(aes(yr, estimate, fill = lab)) +
  geom_col() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number(scale = .001, suffix = "K")) +
  scale_fill_brewer(labels = function(fill) str_wrap(fill, width = 20)) +
  theme_minimal() +
  labs(x = "", y = "", fill = "",
       title = "Race of Householder",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25006)") +
  theme(legend.position = "bottom")
```

```{r}
race %>% ggplot(aes(yr, estimate, fill = lab)) +
  geom_col(position = "fill") +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_percent(scale = 100)) +
  scale_fill_brewer(labels = function(fill) str_wrap(fill, width = 20)) +
  theme_minimal() +
  labs(x = "", y = "", fill = "",
       title = "Race of Householder (Proportion)",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25006)") +
  theme(legend.position = "bottom")
```
