---
title: "Tenure"
execute: 
  echo: false
  warning: false
---

```{r}
library(tidyverse)

v_labs <- read_csv("../_data/v_labs.csv")
acs1_single <- read_csv("../_data/acs1_single.csv")
acs1_multi <- read_csv("../_data/acs1_multi.csv") %>% 
  left_join(v_labs, by = c("variable" = "name"))
```

## Tenure of Population & Households

### Tenure of Households

```{r}
ten <- acs1_multi %>% 
  filter(str_detect(variable, "B25003(?!_001)")) %>% 
  group_by(yr) %>% 
  arrange(estimate) %>% 
  ungroup() %>% 
  mutate(lab = fct_inorder(lab))


ten %>% ggplot(aes(yr, estimate, color = lab)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number(scale = .001, suffix = "K")) +
  scale_fill_brewer(palette = "Set2", direction = -1, 
                    labels = function(fill) str_wrap(fill, width = 20)) +
  theme_minimal() +
  labs(x = "", y = "", color = "",
       title = "Tenure of Households",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25003)") +
  theme(legend.position = "bottom")
```

### Total Population in Occupied Housing Units by Tenure

```{r}
tpohu_t <- acs1_multi %>% 
  filter(str_detect(variable, "B25008(?!_001)")) %>% 
  group_by(yr) %>% 
  arrange(estimate) %>% 
  ungroup() %>% 
  mutate(lab = fct_inorder(lab))


tpohu_t %>% ggplot(aes(yr, estimate, color = lab)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous(labels = scales::label_number(scale = .001, suffix = "K")) +
  scale_fill_brewer(palette = "Set2", direction = -1, 
                    labels = function(fill) str_wrap(fill, width = 20)) +
  theme_minimal() +
  labs(x = "", y = "", color = "",
       title = "Tenure of Total Population in Occupied Housing Units",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25003)") +
  theme(legend.position = "bottom")
```

### Average Household Size by Tenure

```{r}
ahhs_t <- acs1_multi %>% 
  filter(str_detect(variable, "B25010(?!_001)")) %>% 
  group_by(yr) %>% 
  arrange(estimate) %>% 
  ungroup() %>% 
  mutate(lab = fct_inorder(lab))


ahhs_t %>% ggplot(aes(yr, estimate, color = lab)) +
  geom_line() +
  geom_point() +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_fill_brewer(palette = "Set2", direction = -1, 
                    labels = function(fill) str_wrap(fill, width = 20)) +
  theme_minimal() +
  labs(x = "", y = "", color = "",
       title = "Average Household Size by Tenure",
       subtitle = "Memphis, TN (2005-2021)",
       caption = "ACS 1-Year, 2005-2019, 2021 (B25003)") +
  theme(legend.position = "bottom")
```
