project:
  type: website

website:
  title: "Memphis Census"
  sidebar: 
      style: "docked"
      background: dark
      contents: 
        - index.qmd
        - section: "Housing"
          contents: 
            - housing/hsg-units.qmd
            - housing/population.qmd
            - housing/hsg-costs.qmd
            - housing/tenure.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



