project:
  type: website

website:
  title: "Memphis Census"
  sidebar: 
      style: "docked"
      background: dark
      contents: 
        - index.qmd
        - section: "Basics"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



